/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_identity_pool_id": "us-west-1:35ce7406-6f36-4c13-b225-489f12b441fc",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_KZD2affqR",
    "aws_user_pools_web_client_id": "sdb8tojjdud0gpo9ee7i5tul7",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "storagesampleappf6b6a3e5cd1b4fceab6d61ffcd54330143015-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
